### ISSUE TITLE
AdChoice Malware injection via chrome extension update (again)

### ISSUE THREAD

**Issue by jcodling** [CouchPotato/Browser-Extension#13]
The update to the Chrome extension on Oct 08, 2016 injects AdChoice malware.

AdChoice is not some mistake like forgetting a semicolon. It is added deliberately. Once is a mistake. Twice is not.

Nothing like malware infections to lose a user's trust. You just lost any donation I was going to do since this is my first few weeks using this software and I get a malware infection from it.

**Comment by razorloves** [comment]
i can't imagine him doing this intentionally.  what's going on @RuudBurger ?

**Comment by krizzo** [comment]
If he's trying to add something to get financial gain for the development time that's one thing. Forcing it / not letting users choose or even just notifying them is another thing.

The said thing is I just noticed the link while reading an article and knew exactly which extension to disable. Is development being done against the master branch with automatic build and deployment?

**Comment by RuudBurger** [comment]
Could youprovide screenshots? Im testing out some moneyization options and did run this locally for 2 weeks. The ads shouldnt be that bad, and should be blocked by adblock extensions.

**Comment by jcodling** [comment]
> Could youprovide screenshots? Im testing out some moneyization options and did run this locally for 2 weeks. The ads shouldnt be that bad, and should be blocked by adblock extensions.
I'm not screenshotting anything because I'm not reinstalling. The ads are intrusive. They modify the page and break things. AdBlock Plus does not block them at all. This malware is why I use adblock in the first place. It is part of the problem, not the solution.

AdChoice is **malware**. Plain and simple. I completely disagree with it being forced on anyone. This was a poor choice in monetization in my opinion. If you want to put ads in your original app then so be it. Modifying anyone else's content like AdChoice does is on par with the actions of a scam artist or unwanted graffiti. At least graffiti is mostly art. I am disappointed and I only started using CP a few weeks ago.

**Comment by madyoda** [comment]
> Could youprovide screenshots?  

![image](https://cloud.githubusercontent.com/assets/5332144/19220866/3660ebdc-8e2f-11e6-958c-fb6fbb26fe23.png)

**Comment by RuudBurger** [comment]
Thanks. I removed the shit-adding code.
Working on something I can control myself and only loads when adding a movie from the popup.

**Comment by jcodling** [comment]
> Working on something I can control myself and only loads when adding a movie from the popup.

That is a better option. Thank you for reconsidering.

**Comment by jcodling** [comment]
Since this is my issue and it is being taken care of I will close it now.

**Comment by Chintagious** [comment]
@jcodling: Tickets shouldn't be closed until they're actually resolved..

**Comment by jcodling** [comment]
When it's your ticket you can do what you want with it. It's closed to me. I've uninstalled and won't be using it again. I will not use something that does something so insidious on purpose as to infect my machine with malware.
